#%RAML 1.0 Trait
headers:
  Accept?:
    default: application/json
    enum:
      - application/json
      - application/xml
  Content-Type?:
    enum:
      - application/json
      - application/xml
    default: application/json